In [63]:
import pandas as pd
from functools import reduce

In [64]:
mouse_tfs_df = pd.read_csv("./mouse/01_cyt_nuc_TFs/mouse_proteome_TFs.csv", index_col=0)
mouse_cytoskeletal_df = pd.read_csv("./mouse/01_cyt_nuc_TFs/uniprot-compressed_cytoskeletal_mouse.csv")
mouse_nucleus_df = pd.read_csv("./mouse/01_cyt_nuc_TFs/uniprot-compressed_nucleus_MS.csv")

**Combine Cyt, Nuc and TF files**

In [65]:
df_to_combine_list = [mouse_tfs_df, mouse_cytoskeletal_df, mouse_nucleus_df]

In [66]:
#for df in df_to_combine_list:
#    print(df.shape)
    
#for df in df_to_combine_list:
#    print(df.columns)

In [67]:
col_list = ['Entry', 'Reviewed', 'Entry Name', 'Protein names', 'Gene Names',
       'Organism', 'Length', 'Gene Ontology (cellular component)',
       'Subcellular location [CC]', 'Mass', 'Function [CC]',
       'Tissue specificity', 'Gene Ontology (biological process)',
       'Gene Ontology (molecular function)', 'Signal peptide',
       'Transit peptide']

cyt_nuc_df = mouse_cytoskeletal_df.merge(mouse_nucleus_df, on=col_list, how='outer')
cyt_nuc_df.shape

(5634, 16)

In [68]:
col_list = ['Entry', 'Reviewed', 'Entry Name', 'Protein names', 'Gene Names',
       'Organism', 'Length', 'Gene Ontology (cellular component)',
       'Gene Ontology (biological process)',
       'Gene Ontology (molecular function)']

cyt_nuc_tfs_df = cyt_nuc_df.merge(mouse_tfs_df, on=col_list, how='outer')
cyt_nuc_tfs_df.shape

(8472, 18)

**Combine secreted lists**

In [86]:
mouse_secreted_df = pd.read_csv("./mouse/02_secreted/uniprot-compressed_secreted_mouse_08032022.csv")
mouse_secreted_es_df = pd.read_csv("./mouse/02_secreted/uniprot-compressed_Mouse_Extracellular space.csv")
mouse_secreted_ee_df = pd.read_csv("./mouse/02_secreted/uniprot-compressed_Mouse_Extracellular exosome.csv")
mouse_secreted_human_atlas_df = pd.read_csv("./mouse/02_secreted/uniprot-download_true_fields_accession_2Creviewed_2Cid_2Cprotein_nam-2022.08.11-22.05.45.96_mouse_human_atlas.csv")

#endoplasmic reticulum localization 
mouse_0096_df = pd.read_csv("./mouse/02_secreted/ER/uniprot-compressed_Endoplasmic reticulum lumen_SL-0096.csv")
mouse_0097_df = pd.read_csv("./mouse/02_secreted/ER/uniprot-compressed_ER membrane_cc_scl_term_SL-0097.csv")
mouse_0095_df = pd.read_csv("./mouse/02_secreted/ER/uniprot-compressed_ER_cc_scl_term_SL-0095.csv")
mouse_0236_df = pd.read_csv("./mouse/02_secreted/ER/uniprot-compressed_Rough endoplasmic reticulum lumen_SL-0236.csv")
mouse_0237_df = pd.read_csv("./mouse/02_secreted/ER/uniprot-compressed_Rough endoplasmic reticulum membrane_SL-0237.csv")
mouse_0235_df = pd.read_csv("./mouse/02_secreted/ER/uniprot-compressed_Rough endoplasmic reticulum_SL-0235.csv")
mouse_0250_df = pd.read_csv("./mouse/02_secreted/ER/uniprot-compressed_Smooth endoplasmic reticulum membrane_SL-0250.csv")

#HPA ER
mouse_hpa_er_df = pd.read_csv("./mouse/02_secreted/ER/uniprot-download_true_fields_accession_2Creviewed_2Cid_2Cprotein_nam-2022.08.18-22.14.59.14_HPA_mapped_ER_to_mouse.csv")

#found in EV1-100A
mouse_from_ev1_100A = pd.read_csv("./mouse/02_secreted/EV1-100A/uniprot_found_in_EV1-100A.csv")

#ER
mouse_SL_0099 = pd.read_csv("./mouse/02_secreted/golgi/uniprot-compressed_Endoplasmic reticulum-Golgi intermediate compartment membrane_SL-0099.csv")
mouse_SL_0098 = pd.read_csv("./mouse/02_secreted/golgi/uniprot-compressed_Endoplasmic reticulum-Golgi intermediate compartment_SL-0098.csv")
mouse_SL_0132 = pd.read_csv("./mouse/02_secreted/golgi/uniprot-compressed_Golgi apparatus_SL-0132.csv")
mouse_SL_0075 = pd.read_csv("./mouse/02_secreted/golgi/uniprot-compressed_SL-0075_COPI.csv")
mouse_SL_0076 = pd.read_csv("./mouse/02_secreted/golgi/uniprot-compressed_SL-0076_COPI-coated vesicle membrane.csv")
mouse_SL_0099 = pd.read_csv("./mouse/02_secreted/golgi/uniprot-compressed_SL-0133_Golgi Ap Lumen.csv")
mouse_SL_0134 = pd.read_csv("./mouse/02_secreted/golgi/uniprot-compressed_SL-0134_Golgi ap mem.csv")

In [87]:
mouse_secreted_to_combine_list = [mouse_secreted_df, mouse_secreted_es_df, mouse_secreted_ee_df, mouse_secreted_human_atlas_df]

mouse_secreted_ee_df["DNA binding"] = mouse_secreted_ee_df["DNA binding"].astype(str)
mouse_secreted_es_df["Transit peptide"] = mouse_secreted_es_df["Transit peptide"].astype(str)

#for df in mouse_secreted_to_combine_list:
#    print(df.shape)
    
#for df in mouse_secreted_to_combine_list:
#    print(df.columns)

col_list = ['Entry', 'Reviewed', 'Entry Name', 'Protein names', 'Gene Names',
       'Organism', 'Length', 'Gene Ontology (cellular component)',
       'Subcellular location [CC]', 'Mass', 'Function [CC]',
       'Tissue specificity', 'Gene Ontology (biological process)',
       'Gene Ontology (molecular function)', 'Signal peptide',
       'Transit peptide', 'DNA binding', 'Gene Ontology (GO)',
       'Protein families', 'Zinc finger']

es_ee_df = mouse_secreted_es_df.merge(mouse_secreted_ee_df, on=col_list, how='outer')
es_ee_df.shape

col_list = ['Entry', 'Reviewed', 'Entry Name', 'Protein names', 'Gene Names',
       'Organism', 'Length', 'Gene Ontology (cellular component)',
       'Subcellular location [CC]', 'Function [CC]', 'Mass',
       'Tissue specificity', 'Gene Ontology (biological process)',
       'Signal peptide', 'Transit peptide']

secreted_es_ee_df = es_ee_df.merge(mouse_secreted_df, on=col_list, how='outer')
secreted_es_ee_df.shape

col_list = ['Entry', 'Reviewed', 'Entry Name', 'Protein names', 'Gene Names',
       'Organism', 'Length', 'Gene Ontology (biological process)',
       'Gene Ontology (GO)', 
       'Gene Ontology (cellular component)',
       'Gene Ontology (molecular function)']

secreted_es_ee_atlas_df = secreted_es_ee_df.merge(mouse_secreted_human_atlas_df, on=col_list, how='outer')
secreted_es_ee_atlas_df.shape

#6952, 21

(6952, 21)

In [88]:
mouse_secreted_er_to_combine_list = [mouse_0096_df, mouse_0097_df, mouse_0095_df, mouse_0236_df, mouse_0237_df, mouse_0235_df, mouse_0250_df]

mouse_0096_df["DNA binding"] = mouse_0096_df["DNA binding"].astype(str)
mouse_0096_df["Transit peptide"] = mouse_0096_df["Transit peptide"].astype(str)
mouse_0096_df["Zinc finger"] = mouse_0096_df["Zinc finger"].astype(str)

mouse_0097_df["Transit peptide"] = mouse_0097_df["Transit peptide"].astype(str)

mouse_0236_df["DNA binding"] = mouse_0236_df["DNA binding"].astype(str)
mouse_0236_df["Transit peptide"] = mouse_0236_df["Transit peptide"].astype(str)
mouse_0236_df["Zinc finger"] = mouse_0236_df["Zinc finger"].astype(str)

mouse_0237_df["DNA binding"] = mouse_0237_df["DNA binding"].astype(str)
mouse_0237_df["Transit peptide"] = mouse_0237_df["Transit peptide"].astype(str)

mouse_0235_df["DNA binding"] = mouse_0235_df["DNA binding"].astype(str)
mouse_0235_df["Transit peptide"] = mouse_0235_df["Transit peptide"].astype(str)

mouse_0250_df["DNA binding"] = mouse_0250_df["DNA binding"].astype(str)
mouse_0250_df["Transit peptide"] = mouse_0250_df["Transit peptide"].astype(str)
mouse_0250_df["Zinc finger"] = mouse_0250_df["Zinc finger"].astype(str)
mouse_0250_df["Signal peptide"] = mouse_0250_df["Signal peptide"].astype(str)
mouse_0250_df["Tissue specificity"] = mouse_0250_df["Tissue specificity"].astype(str)

#for df in mouse_secreted_er_to_combine_list:
#    print(df.shape)
    
#for df in mouse_secreted_er_to_combine_list:
#    print(df.columns)

col_list = ['Entry', 'Reviewed', 'Entry Name', 'Protein names', 'Gene Names',
       'Organism', 'Length', 'Gene Ontology (cellular component)',
       'Subcellular location [CC]', 'Mass', 'Function [CC]',
       'Tissue specificity', 'Gene Ontology (biological process)',
       'Gene Ontology (molecular function)', 'Signal peptide',
       'Transit peptide', 'DNA binding', 'Gene Ontology (GO)',
       'Protein families', 'Zinc finger']

merged_df_er_secreted_mouse = reduce(lambda x, y: pd.merge(x, y, on = col_list, how='outer'), mouse_secreted_er_to_combine_list)
merged_df_er_secreted_mouse.shape

#2158, 20

(2158, 20)

In [89]:
merged_df_er_secreted_mouse["Mass"] = merged_df_er_secreted_mouse["Mass"].astype(str)
#merged_df_er_secreted_mouse.dtypes

secreted_es_ee_atlas_df["Zinc finger"] = secreted_es_ee_atlas_df["Zinc finger"].astype(str)
secreted_es_ee_atlas_df["Mass"] = secreted_es_ee_atlas_df["Mass"].astype(str)
#secreted_es_ee_atlas_df.dtypes

col_list = ['Entry', 'Reviewed', 'Entry Name', 'Protein names', 'Gene Names',
       'Organism', 'Length', 'Gene Ontology (cellular component)',
       'Subcellular location [CC]', 'Mass', 'Function [CC]',
       'Tissue specificity', 'Gene Ontology (biological process)',
       'Gene Ontology (molecular function)', 'Signal peptide',
       'Transit peptide', 'DNA binding', 'Gene Ontology (GO)',
       'Protein families', 'Zinc finger']

secreted_final = secreted_es_ee_atlas_df.merge(merged_df_er_secreted_mouse, on=col_list, how='outer')
secreted_final.shape

#9110,21

(9110, 21)

In [90]:
mouse_hpa_er_df.shape

col_list = ['Entry', 'Reviewed', 'Entry Name', 'Protein names', 'Gene Names',
       'Organism', 'Length', 'Gene Ontology (biological process)',
       'Gene Ontology (GO)', 'Gene Ontology IDs',
       'Gene Ontology (cellular component)',
       'Gene Ontology (molecular function)']

secreted_final_with_hpa_er = secreted_final.merge(mouse_hpa_er_df, on=col_list, how='outer')
secreted_final_with_hpa_er.shape

#10945, 21

(10945, 21)

In [91]:
#secreted_final_with_hpa_er.dtypes

mouse_from_ev1_100A["DNA binding"] = mouse_from_ev1_100A["DNA binding"].astype(str)
mouse_from_ev1_100A["Gene ontology (GO)"] = mouse_from_ev1_100A["Gene Ontology (GO)"].astype(str)
mouse_from_ev1_100A["Transit peptide"] = mouse_from_ev1_100A["Transit peptide"].astype(str)
mouse_from_ev1_100A["Mass"] = mouse_from_ev1_100A["Mass"].astype(str)
#mouse_from_ev1_100A.dtypes

col_list = ['Entry', 'Reviewed', 'Entry Name', 'Protein names', 'Gene Names',
       'Organism', 'Length', 'Gene Ontology (cellular component)',
       'Subcellular location [CC]', 'Mass', 'Function [CC]',
       'Tissue specificity', 'Gene Ontology (biological process)',
       'Gene Ontology (molecular function)', 'Signal peptide',
       'Transit peptide', 'DNA binding', 'Gene Ontology (GO)',
       'Protein families', 'Zinc finger']

final_secreted_merged_with100A = secreted_final_with_hpa_er.merge(mouse_from_ev1_100A, on=col_list, how='outer')
final_secreted_merged_with100A.shape

#10950, 23

(10950, 23)

In [92]:
#final_secreted_merged_with100A = final_secreted_merged_with100A.drop_duplicates('Entry', keep='last')
#final_secreted_merged_with100A.shape
#8361, 23
#final_secreted_merged_with100A.to_csv("./mouse/00_combined/mouse_TP_list_secreted.csv", index=False)

In [93]:
mouse_golgi_list = [mouse_SL_0099, 
                    mouse_SL_0098, 
                    mouse_SL_0132, 
                    mouse_SL_0075,
                    mouse_SL_0076, 
                    mouse_SL_0099, 
                    mouse_SL_0134] 

#for df in mouse_golgi_list:
#    print(df.shape)
    
#for df in mouse_golgi_list:
#    print(df.dtypes)
#    print(df.columns)

mouse_SL_0099["DNA binding"] = mouse_SL_0099["DNA binding"].astype(str)
mouse_SL_0099["Transit peptide"] = mouse_SL_0099["Transit peptide"].astype(str)
mouse_SL_0099["Zinc finger"] = mouse_SL_0099["Zinc finger"].astype(str)

mouse_SL_0098["Transit peptide"] = mouse_SL_0098["Transit peptide"].astype(str)
mouse_SL_0098["Zinc finger"] = mouse_SL_0098["Zinc finger"].astype(str)

mouse_SL_0075["DNA binding"] = mouse_SL_0075["DNA binding"].astype(str)
mouse_SL_0075["Transit peptide"] = mouse_SL_0075["Transit peptide"].astype(str)
mouse_SL_0075["Zinc finger"] = mouse_SL_0075["Zinc finger"].astype(str)

mouse_SL_0076["DNA binding"] = mouse_SL_0076["DNA binding"].astype(str)
mouse_SL_0076["Transit peptide"] = mouse_SL_0076["Transit peptide"].astype(str)
mouse_SL_0076["Zinc finger"] = mouse_SL_0076["Zinc finger"].astype(str)

mouse_SL_0099["DNA binding"] = mouse_SL_0099["DNA binding"].astype(str)
mouse_SL_0099["Transit peptide"] = mouse_SL_0099["Transit peptide"].astype(str)
mouse_SL_0099["Zinc finger"] = mouse_SL_0099["Zinc finger"].astype(str)

mouse_SL_0134["Transit peptide"] = mouse_SL_0134["Transit peptide"].astype(str)

merged_df_golgi = reduce(lambda x, y: pd.merge(x, y, on = col_list, how='outer'), mouse_golgi_list)
merged_df_golgi.shape

#1559, 20

(1559, 20)

In [94]:
merged_df_golgi["Mass"] = merged_df_golgi["Mass"].astype(str)

col_list = ['Entry', 'Reviewed', 'Entry Name', 'Protein names', 'Gene Names',
       'Organism', 'Length', 'Gene Ontology (cellular component)',
       'Subcellular location [CC]', 'Mass', 'Function [CC]',
       'Tissue specificity', 'Gene Ontology (biological process)',
       'Gene Ontology (molecular function)', 'Signal peptide',
       'Transit peptide', 'DNA binding', 'Gene Ontology (GO)',
       'Protein families', 'Zinc finger']

final_secreted_merged_withgolgi = final_secreted_merged_with100A.merge(merged_df_golgi, on=col_list, how='outer')
final_secreted_merged_withgolgi.shape

#12152, 23

(12152, 23)

In [95]:
final_secreted_merged_withgolgi = final_secreted_merged_withgolgi.drop_duplicates('Entry', keep='last')
final_secreted_merged_withgolgi.shape

#8981, 23

(8981, 23)

In [96]:
#change alternative name for 
#- E9QAT4 to A2AIX1
#- Q61810 to F8VQ06
final_secreted_merged_withgolgi["Entry"].replace("E9QAT4", "A2AIX1", inplace=True)
final_secreted_merged_withgolgi['alternative uniprot ID'].replace("A2AIX1", "E9QAT4", inplace=True)
final_secreted_merged_withgolgi["Entry"].replace("Q61810", "F8VQ06", inplace=True)
final_secreted_merged_withgolgi['alternative uniprot ID'].replace("F8VQ06", "Q61810", inplace=True)

In [97]:
#subset to check 
final_secreted_merged_withgolgi[final_secreted_merged_withgolgi["Entry"]=='A2AIX1']

,Entry,Reviewed,Entry Name,Protein names,Gene Names,Organism,Length,Gene Ontology (cellular component),Subcellular location [CC],Mass,...,Gene Ontology (molecular function),Signal peptide,Transit peptide,DNA binding,Gene Ontology (GO),Protein families,Zinc finger,Gene Ontology IDs,alternative uniprot ID,Gene ontology (GO)
10946,A2AIX1,reviewed,SC16A_MOUSE,Protein transport protein Sec16A (SEC16 homolo...,Sec16a Kiaa0310 Sec16,Mus musculus (Mouse),2357,cytosol [GO:0005829]; endoplasmic reticulum ex...,SUBCELLULAR LOCATION: Endoplasmic reticulum me...,254202,...,NaN,NaN,nan,nan,cytosol [GO:0005829]; endoplasmic reticulum ex...,SEC16 family,NaN,NaN,E9QAT4,cytosol [GO:0005829]; endoplasmic reticulum ex...

In [98]:
final_secreted_merged_withgolgi[final_secreted_merged_withgolgi["Entry"]=='F8VQ06']

,Entry,Reviewed,Entry Name,Protein names,Gene Names,Organism,Length,Gene Ontology (cellular component),Subcellular location [CC],Mass,...,Gene Ontology (molecular function),Signal peptide,Transit peptide,DNA binding,Gene Ontology (GO),Protein families,Zinc finger,Gene Ontology IDs,alternative uniprot ID,Gene ontology (GO)
10947,F8VQ06,reviewed,LTBP3_MOUSE,Latent-transforming growth factor beta-binding...,Ltbp3,Mus musculus (Mouse),1253,collagen-containing extracellular matrix [GO:0...,SUBCELLULAR LOCATION: Secreted {ECO:0000250|Un...,134363,...,calcium ion binding [GO:0005509]; transforming...,"SIGNAL 1..38; /evidence=""ECO:0000255""",nan,nan,collagen-containing extracellular matrix [GO:0...,LTBP family,NaN,NaN,Q61810,collagen-containing extracellular matrix [GO:0...

In [99]:
final_secreted_merged_withgolgi.to_csv("./mouse/00_combined/mouse_TP_list_secreted.csv", index=False)
final_secreted_merged_withgolgi.shape

#8981,23

(8981, 23)

**Remove overlapping uniprot IDs with secreted df**

In [111]:
secreted_uniprot_list = final_secreted_merged_withgolgi["Entry"].tolist()
len(secreted_uniprot_list)

#8981

8981

In [112]:
unique_cyt_nuc_tfs_df = cyt_nuc_tfs_df[~cyt_nuc_tfs_df["Entry"].isin(secreted_uniprot_list)]

In [113]:
unique_cyt_nuc_tfs_df.shape

#7971, 18

(7971, 18)

In [114]:
unique_cyt_nuc_tfs_df = unique_cyt_nuc_tfs_df.drop_duplicates('Entry', keep='last')
unique_cyt_nuc_tfs_df.shape

#7971, 18

(7971, 18)

In [115]:
unique_cyt_nuc_tfs_df.to_csv("./mouse/00_combined/mouse_FP_list_cyt_nuc_TFs.csv", index=False)